fragment StoryParts on Story {
  __typename
  title
  series
  series_order
  tags
  author
  draft
  body
}

fragment PostParts on Post {
  __typename
  title
  tags
  categories
  author
  date
  showDate
  dateUpdated
  showDateUpdated
  draft
  body
}
