baseURL = 'https://greenboi.me/'
languageCode = 'en-us'
title = "Verdant Homeland"
author = "Emerald"
theme = "risotto"


[params.theme]
palette = "dark-mode"
mode = "dark-mode"

[params.about]
title = "The Greenzone"
description = "Abandon hope, all ye who enter here"

[[params.socialLinks]]
icon = "fab fa-git-alt"
title = "Gitea"
url = "https://gitea.greenboi.me/Emerald/"

[[params.socialLinks]]
icon = "fab fa-mastodon"
title = "Fediverse"
url = "https://uwu.social/@emerald"

[[params.socialLinks]]
icon = "fas fa-headset"
title = "Owncast"
url = "https://live.greenboi.me"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/index.html"
    weight = 10
    
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/index.html"
    weight = 2
    
  [[menu.main]]
    identifier = "discord"
    name = "Discord"
    url = "https://tf.greenboi.me/discord"
    weight = 100
    
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects"
    weight = 9

