title = 'Technically A Website'
baseURL = 'https://greenboi.me'
languageCode = 'en-us'
enableRobotsTXT = true
copyright = "©2025 Emerald"

[params.author]
email = 'emerald@emeraldgreen.dev'
name = 'Emerald'

[taxonomies]
series = 'series'
tag = 'tags'
category = 'categories'

# [[params.webrings]]
# name = "example webring"
# href = "https://example.com"


[build.buildStats]
enable = true

[module.hugoVersion]
extended = false
min = "0.148.0"

[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "hugo_stats.json"
target = "assets/watching/hugo_stats.json"
