baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Technically A Website'
summaryLength = 10

[taxonomies]
series = 'series'


# [[params.webrings]]
# name = "example webring"
# href = "https://example.com"
